data cust;
set retail.custadd (obs=100000 keep=pcnumber postcode);
*where pcnumber ne '';

if ranuni(0)*15 lt 1 ;

format  POST $8.;
informat POST $8.;
LENGTH LAST2 $2. LAST3 $1. MID1-MID2 $1. FIRST1-FIRST4 $1. NEWPOST $8. POSTCODE $8.;

POST=COMPRESS(POSTcode,' ');
IF POST='' THEN REJECT=9;
IF POST='NULL' THEN REJECT=9;

POSTCOD2=LEFT(SUBSTR(RIGHT(POST),1,5));

LAST2=SUBSTR(RIGHT(POST),7,2);
IF SUBSTR(LAST2,2,1) LT 'A' THEN REJECT=1;
IF SUBSTR(LAST2,2,1) LT 'A' THEN REJECT=1;

LAST3=SUBSTR(RIGHT(POST),6,1);
IF LAST3='O' THEN LAST3=0;
IF LAST3='I' THEN LAST3=1;
IF LAST3 GT '9' THEN REJECT=2;


FIRST1=SUBSTR(POSTCOD2,1,1);
IF FIRST1='0' THEN FIRST1='O';
IF FIRST1='1' THEN FIRST1='I';
IF FIRST1 LE '9' THEN REJECT=3;

FIRST2=SUBSTR(POSTCODE,2,1);
FIRST3=SUBSTR(POSTCODE,3,1);
FIRST4=SUBSTR(POSTCODE,4,1);

IF FIRST2='0' THEN FIRST2='O';
IF FIRST2='I' THEN FIRST2='1';
IF FIRST2 LT 'A' THEN DO;
FIRST4=FIRST3;
FIRST3=FIRST2;
FIRST2=' ';
END;

MID1=SUBSTR(RIGHT(FIRST3||FIRST4),1,1);
MID2=SUBSTR(RIGHT(FIRST3||FIRST4),2,1);

IF MID1='I' THEN MID1='1';
IF MID1='O' THEN MID1='0';
IF MID1 GT '9' THEN REJECT=4;

IF MID2='I' THEN MID2='1';
IF MID2='O' THEN MID2='0';

NEWPOST=FIRST1||FIRST2||MID1||MID2||' '||LAST3||LAST2;
proc sort;
by newpost;
RUN;

data cust2;
merge cust (rename=(newpost=postcode)) sally.sally;
by postcode;
run;
