DATA WORK.ONE;
  DO I=1 TO 100;
     ID=I;OUTPUT;
  END;
KEEP ID;


DATA WORK.ONE;SET WORK.ONE; SCORE=RANUNI(0);
  SCORE=1000*ROUND(SCORE,.001);  *  CREATE SCORES BETWEEN 1 AND 1000;

  SCOREC = 100*CEIL(SCORE/100);    *  HOW TO ROUND UP TO NEXT 100     ;
  SCOREF = 100*FLOOR(SCORE/100);   *  HOW TO ROUND DOWN TO NEXT 100   ;

PROC PRINT DATA=WORK.ONE;
RUN;
