options symbolgen; /*Controls whether the results of resolving macro variable references are written to the SAS log*/
options MLOGIC; /*Controls whether SAS traces execution of the macro language processor */
options MAUTOLOCDISPLAY; /*Displays the source location of the autocall macros in the log when the autocall macro is invoked*/
options MPRINT; /*Displays SAS statements that are generated by macro execution */
options COMPRESS=YES; /*Controls the compression of observations in output SAS data sets */
options msglevel=I; /*Controls the level of detail in messages that are written to the SAS log*/
options missing=' '; /*Set missing data elements to show as whitespace (rather than .)*/
options obs=MAX; /*Specifies when to stop processing observations or records*/
options replace; /*Controls whether you can replace permanently stored SAS data sets */
